language: java
jdk:
- openjdk8
before_install:
- chmod +x gradlew
- "./gradlew setupDecompWorkspace"
deploy:
  provider: releases
  api_key:
    secure: GV6VEpKw8t5MyHVnv7PJqlIVXxXLmwTmMY9LMKRkCo475/SPC9R1JGR9awudpHlJSJWenaGyDRBCQpnbK4K/LeJHRByvTjBbZHQ5ZYELgwmwjG3L8W4dLgjEhltbJdvVChezEA4b8W3IFYr2K0vt8N9JUceIAUVmDA6X81e3boe99qyX8AOg0qXUIjVEWj0hgaXTe66Z7cylVe2po5LMO3Ke+gsdgRV2WZorX4Bc+DlYmdTXaOkGeUTZgOmju3Hv0LL6cezf/YZ2bV2d3+ZNgJc5nOaSxaE+LRP9MXn8oP7rqIxFWQU13AV24vwcK4L6EYpQ8eSDOXg4/DY13vHRNpdQHyb3Bqt6oDw86cD0wBEaZzG8tXlPYxxGsB99DvcVAUEFQSwCdQplS7Vidh29cEwl06olDVfjLfsaMxTceZ/iQLZgBCgVcDHJNo18/GkKiW5ut6lIPeNxV2S8aAmcQO57Ko0e3jhGgMe7JX/itdZIVDqM37maNVFJkczLsl0RuQGKRGBjNFxOgd/wHQsUKHXzbVbq4PjzzPbTwVWu6tzcpSoA7ZYVToyfoJ+jBogc3mZ0Khb/8BpVHu4aBQyI1rTdnV44v6GaMNrBUyT/yzpgScRYz1yC+4d8TM7CWgbWaOPYdq7jYIX6LMRx2tXDRu3oGdJvUrn/Plx5Upb6wYw=
  file: build/libs/KAMI-*-release.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: zeroeightysix/KAMI
    tags: true
